### ISSUE TITLE
Respect the string content in shared_versions.yaml

### ISSUE THREAD

**Issue by littleGnAl** [littleGnAl/shared_versions#2]
```
# shared_versions.yaml
shared_versions:
  git:
    ref: '55e3770'
```
After run command, the `'` is lost.
